export type Banner = {
  imageUrl: string;
  targetId: number;
  adid: null;
  targetType: number;
  titleColor: string;
  typeTitle: string;
  url: null | string;
  exclusive: boolean;
  monitorImpress: null;
  monitorClick: null;
  monitorType: null;
  monitorImpressList: null;
  monitorClickList: null;
  monitorBlackList: null;
  extMonitor: null;
  extMonitorInfo: null;
  adSource: null;
  adLocation: null;
  adDispatchJson: null;
  encodeId: string;
  program: null;
  event: null;
  video: null;
  song: null;
  scm: string;
  bannerBizType: string;
};

export type HotRecommendProps = {
  id: number;
  type: number;
  name: string;
  copywriter: string;
  picUrl: string;
  canDislike: boolean;
  trackNumberUpdateTime: number;
  playCount: number;
  trackCount: number;
  highQuality: boolean;
  alg: string;
};

export type Album = {
  songs: any[];
  paid: boolean;
  onSale: boolean;
  mark: number;
  awardTags: null;
  companyId: number;
  blurPicUrl: null | string;
  alias: any[];
  artists: Artist[];
  copyrightId: number;
  picId: number;
  artist: Artist2;
  pic: number;
  briefDesc: string;
  publishTime: number;
  company: string;
  picUrl: string;
  commentThreadId: string;
  tags: string;
  description: string;
  status: number;
  subType: string;
  name: string;
  id: number;
  type: string;
  size: number;
  picId_str?: string;
  transNames?: string[];
};
type Artist2 = {
  img1v1Id: number;
  topicPerson: number;
  alias: string[];
  picId: number;
  followed: boolean;
  trans: string;
  musicSize: number;
  albumSize: number;
  briefDesc: string;
  picUrl: string;
  img1v1Url: string;
  name: string;
  id: number;
  picId_str?: string;
  img1v1Id_str: string;
  transNames?: string[];
};
type Artist = {
  img1v1Id: number;
  topicPerson: number;
  alias: any[];
  picId: number;
  followed: boolean;
  trans: string;
  musicSize: number;
  albumSize: number;
  briefDesc: string;
  picUrl: string;
  img1v1Url: string;
  name: string;
  id: number;
  img1v1Id_str: string;
};
